### ISSUE TITLE
MslUserIdTokenException ctor doesn't accept Throwable

### ISSUE THREAD

**Issue by quidryan** [Netflix/msl#57]
The underlying MslException accepts a Throwable as a cause, but MslUserIdTokenException doesn't.

**Comment by wmiaw** [comment]
Many of the MslException subclasses don't have all possible combinations of parameters on the defined constructors. They only have constructors defined for the parameter combinations that are actually used. (Might be some leftovers from earlier code, but that's the idea.)

Do you have a use case for throwing a MslUserIdTokenException due to some other exception? If so then we should add a new constructor which has the parameter combination you need. Right now this exception is only thrown when the User ID Token was revoked, since the description for the exception is that the User ID Token was successfully parsed but there is some other problem with it.

**Comment by quidryan** [comment]
Our renewUserIdToken is calling a backend server. If that server reports a failure, I want to be able to throw a MslUserIdTokenException with the underlying exception as the cause.

**Comment by wmiaw** [comment]
Makes sense. We should add the new constructor then. Feel free to submit a pull request with the parameter combination you want.

**Comment by quidryan** [comment]
Yep, that works.
