### ISSUE TITLE
Schemes should be able to add Service Tokens

### ISSUE THREAD

**Issue by quidryan** [Netflix/msl#68]
If Key Exchange or Entity Auth learn something about an entity, they should be able to contribute entity bound service tokens.

User Auth Schemes should also be able to contribute user-bound tokens.

KeyX/EntityAuth being able to contribute User bound tokens, though not the other way, ie. User Auth Scheme shouldn't be able to provide Entity bound service tokens. This would also be for deficient implementations that only store user-bound tokens.

**Comment by wmiaw** [comment]
This is not possible as described, because authentication does not imply creation of master or user ID tokens.

Entity authentication is not directly involved in master token creation, and creation of a user ID token does not even require user authentication to occur in one case.

If a MSL configuration wishes to carry information about key exchange forward, the best approach is probably to do so via the TokenFactory if the master token is being created. See #81. The issuer data in both master token and user ID token are currently designed for use by the TokenFactory.

Service tokens should only be managed by and properly bound by the application layer above MSL.
